---

- name: Install package
  apt: name=nginx state=present default_release=testing

- name: Configure service
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Create Diffie-Hellmann parameters
  command: /usr/bin/openssl dhparam -out /etc/ssl/dhparams.pem 4096 creates=/etc/ssl/dhparams.pem
  notify: restart nginx

- name: Enable service
  service: name=nginx enabled=yes
